import { LocalizationType } from 'types/appTypes'

export const localization: LocalizationType = {
    pl: {
        home: {
            lesson: 'Lekcja',
            math: 'Matematyka',
            english: 'Angielski',
            spelling: 'Ortografia (wkrótce)',
            lastResults: 'Ostatnie wyniki',
        },
        testName: {
            addition: 'Dodawanie',
            subtraction: 'Odejmowanie',
            multiplication: 'Mnożenie',
            division: 'Dzielenie',
            bodyParts: 'Części ciała',
            family: 'Rodzina',
            animals: 'Zwierzęta',
            birthday: 'Urodziany',
            clothesEasy: 'Ubrania 1',
            clothes: 'Ubrania 2',
            colorsEasy: 'Kolory 1',
            colors: 'kolory 2',
            house: 'Dom',
            numbersEasy: 'Liczby 1-10',
            numbers: 'Liczby 1-20',
            positions: 'Położenie',
            time: 'Czas',
            unit4: 'Unit 4',
        },
        setup: {
            settings: 'Ustawienia',
            yourName: 'Twoje imię',
            numberOfQuestions: 'Liczba pytań',
            operation: 'Działanie',
            topic: 'Temat',
            range: 'Zakres',
            incorrectNameMgs: 'Imię musi mieć od 3 do 20 znaków',
        },
        test: {
            questionNo: 'Pytanie nr ',
            translate: 'Przetłumacz:',
            howMuch: 'Ile wynosi: ',
            nextQuestion: 'Następne pytanie',
            lazyLoadingError: 'Ups... coś poszło nie tak. Sprawdź proszę połączenie z internetem.',
        },
        summary: {
            yourResult: 'Twój wynik to',
            master: 'Mistrzunio!',
            notBad: 'Nieźle :)',
            couldBeBetter: 'Nie ma tragedii',
            poor: 'Cienizna :(',
            repeatTest: 'Powtórz test',
            answers: 'Odpowiedzi',
            shouldBe: 'powinno być',
        },
        results: {
            time: 'czas',
            noLastResults: 'Brak ostatnich wyników',
        },
    },
    cz: {
        home: {
            lesson: 'Lekce',
            math: 'Matematika',
            english: 'Angličtina',
            spelling: 'Pravopis (polština)',
            lastResults: 'Nedávné výsledky',
        },
        testName: {
            addition: 'Sčítání',
            subtraction: 'Odčítání',
            multiplication: 'Násobení',
            division: 'Dělení',
            bodyParts: 'Části těla',
            family: 'Rodina',
            animals: 'Zvířata',
            birthday: 'Narozeniny',
            clothesEasy: 'Oblečení 1',
            clothes: 'Oblečení 2',
            colorsEasy: 'Kolory 1',
            colors: 'kolory 2',
            house: 'Doma',
            numbersEasy: 'Čísla 1-10',
            numbers: 'Čísla 1-20',
            positions: 'Pozice',
            time: 'Čas',
            unit4: 'Unit 4',
        },
        setup: {
            settings: 'Nastavení',
            yourName: 'Své jméno',
            numberOfQuestions: 'Počet otázek',
            operation: 'Operace',
            topic: 'Téma',
            range: 'Rozsah',
            incorrectNameMgs: 'Jméno musí mít 3 až 20 znaků',
        },
        test: {
            questionNo: 'Otázka č. ',
            translate: 'Přeložit:',
            howMuch: 'Jak moc je: ',
            nextQuestion: 'Další otázka',
            lazyLoadingError:
                'Jejda! Něco se pokazilo. Zkontrolujte prosím své internetové připojení.',
        },
        summary: {
            yourResult: 'Tvůj výsledek',
            master: 'Mistr!',
            notBad: 'Není to špatné',
            couldBeBetter: 'Mohlo by být lépe',
            poor: 'Špatně :(',
            repeatTest: 'Zopakujte test',
            answers: 'Odpovědi',
            shouldBe: 'by měl',
        },
        results: {
            time: 'čas',
            noLastResults: 'Žádné nedávné výsledky',
        },
    },
}
